### ISSUE TITLE
feat: allow or forbid Batch Download feature for a given project

### ISSUE THREAD

**Issue by mvanzalu** [ICIJ/datashare#1094]
**Is your feature request related to a problem? Please describe.**
We want to allow or forbid the Batch Download feature for the projects.

**Describe a possible solution**
We can add a new field in Project table and an attribute in the model such as `isBatchDownloadAllowed`, check this value in `BatchDownloadLoop` and modify the display in the frontend accordingly

**Comment by bamthomas** [comment]
Actually batch download is making one request to elasticsearch, and then is getting the source files within the hierarchy of files on disk. This can be costly in case there are embedding files. But it won't be costly for ES. 

So I wonder if the hypothesis is that slow request response time are caused by batch download is correct.

Maybe we can monitor the batch download times and try to match with slow response time to see if they is correlation.
