### ISSUE TITLE
design system: project button

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1444]
* [x] project label
* [x] project button
* [x] project link
* [x] project thumbnail
* [x] project dropdown selector

**Comment by pirhoo** [comment]
Components are here:

* https://icij.github.io/datashare-client/?path=/docs/components-project-projectbutton--docs
* https://icij.github.io/datashare-client/?path=/docs/components-project-projectdropdownselector--docs
* https://icij.github.io/datashare-client/?path=/docs/components-project-projectlabel--docs

**Comment by Soliine** [comment]
Great!
I should have designed it before so I am sorry about that but to be more consistent with the rest of the design system, I suggest this dropdown selector:
<img width="161" alt="Screenshot 2024-07-18 at 12 33 07" src="https://github.com/user-attachments/assets/6d79afc1-9be3-4472-b50f-44dd0612fb72">
Note that I remove the pink border when the dropdown is open because it would make two pink borders when user hovers the "search filters" field (and I tried and it's too much pink!)

**Comment by pirhoo** [comment]
OK no problem, I'm gonna try to apply a similar style to all dropdown menu.

**Comment by pirhoo** [comment]
The new component is here: https://icij.github.io/datashare-client/?path=/docs/components-project-projectdropdownselector-projectdropdownselector--docs

**Comment by pirhoo** [comment]
We must:

* not close the dropdown on "select all"
* check the first item when unchecking "select all"

**Comment by pirhoo** [comment]
Done!

**Comment by Soliine** [comment]
Perfect!
