### ISSUE TITLE
design system: document user actions

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1451]
![Image](https://github.com/user-attachments/assets/2ed11a89-57aa-4f13-abd3-b0eb2033c45b)

**Comment by caro3801** [comment]
https://icij.github.io/datashare-client/?path=/docs/components-document-documentuseractions-documentuseractions--docs

**Comment by Soliine** [comment]
Great!

I see that:

- in dark mode, we cannot read the icon and text, in the design they are in action-body-subtle. But I see that the issue is in DocumentUserActionsEntry and not in DocumentUserActions so don't take this into account if it is not relevant
![Image](https://github.com/user-attachments/assets/d4d793c6-fb24-4215-96c3-b8b88de53136)

- in the design, on hover, they have a 6 radius on all corners and they don't take the whole bar's height, is it possible to have the same?
![Image](https://github.com/user-attachments/assets/576d3797-2792-42be-801a-9cb973451905)

- there is also a hidden tooltip issue that I already saw elsewhere, can you tell me if it is just a storybook appearance issue or a real issue?
![Image](https://github.com/user-attachments/assets/576d3797-2792-42be-801a-9cb973451905)

- the designed tooltip text is "3 tags" while it is "Tags (3)" in Storybook
![Image](https://github.com/user-attachments/assets/88cc00cd-ac89-4e47-9ee8-7e46f8e6349b)

**Comment by caro3801** [comment]
Fixed text presentation, rounded button and dark mode.
Added compact mode

**Comment by Soliine** [comment]
Awesome!

I don't see three dots in the compact mode, is it normal?
<img width="424" alt="Screenshot 2024-07-31 at 11 31 18" src="https://github.com/user-attachments/assets/60325a0a-4a7c-495c-a70a-eff43b6bdb49">

**Comment by caro3801** [comment]
Compact mode is ready to review 
https://icij.github.io/datashare-client/?path=/story/components-document-documentuseractions-documentuseractions--dropdown-default

**Comment by Soliine** [comment]
Awesome! Great work ! 💪

I see these details:

- Can you put label in singular if value is 0 ("0 folder")?
<img width="175" alt="Screenshot 2024-08-06 at 13 55 01" src="https://github.com/user-attachments/assets/29c947be-9aab-4b8a-bb46-dac4475d8d91">

- If it doesn't take too much time only: I know height won't be an issue as you said but in order to match the design's aesthetics elsewhere, could you make the size of the entries less high so we still see the bar's background below and above the entry?
<img width="350" alt="Screenshot 2024-08-06 at 14 11 36" src="https://github.com/user-attachments/assets/9c7e2a64-fcb7-4a63-8a32-d2658972e182">

- In compact mode, could we have the option to have the labels' texts (not only numbers) in the dropdown when the screen is large enough?
<img width="167" alt="Screenshot 2024-08-06 at 14 13 42" src="https://github.com/user-attachments/assets/8b56645b-1a0a-4a98-9d00-b4cabb275fcf">

The rest is fantastic!

**Comment by Soliine** [comment]
It's what we call perfection 👑
