### ISSUE TITLE
design system: page table

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1470]
* [x] PageTable
* [x] PageTableTh
* [x] PageTableThSort
* [x] PageTableTr
* [x] PageTableTdActions

**Preview**

![Image](https://github.com/user-attachments/assets/71278617-2832-4009-93e4-a61a1e8e97f8)

**Comment by Soliine** [comment]
Big big work!

- When I hover the header (PageTableTh) of a small column, I cannot see the sort icon. is it a bug due to the size of the column or because you set them to unsortable?

- Can you right-align any column with numbers (like Page) or is it complicated?
<img width="629" alt="Screenshot 2024-07-29 at 15 22 35" src="https://github.com/user-attachments/assets/cf50711f-c296-4c9f-85ea-20ab3850df27">

- Will we be able to have both Selectmode and the status and privacy columns?

**Comment by pirhoo** [comment]
* the narrow columns where you don't see the sort button are just columns where it's not activated
* regarding right-alignment for numbers, here it's just an example of usage of table, we will adjust the formatting later on page where we use tables. I right align the storybook anyway.
* the status display is just an regular column so no problem to have it with the select mode
* the actions buttons here are just example, no the real buttons

**Comment by Soliine** [comment]
Ok great! Thanks for taking the time to explain
