### ISSUE TITLE
design system: batch search details

### ISSUE THREAD

**Issue by caro3801** [ICIJ/datashare#1487]
- [x] batch search details title
- [x] batch search details actions (slot?)
- [x] batch search details status

![Image](https://github.com/user-attachments/assets/b83fd164-c823-4015-90ad-11b37a0274f8)

**Comment by caro3801** [comment]
Component is here: https://icij.github.io/datashare-client/?path=/story/components-batchsearch-batchsearchcard--default
Two remarks: 
* not sure what "enter" does so I did not add it
* rename and edit properties actions are very similar. maybe some design investigation needed here.

**Comment by Soliine** [comment]
Great job 👍 👍  

Your two points are right, good catch!

- "Enter": when I change the component, sometimes the instances are also changed (while they shouldn't be as the text is a property but I don't get why it does that sometimes and not on other buttons, like on the one below here... but I don't get why). Originally, it was not Enter but "Download 2,745 queries" as in the older version below so it should be like this:
![Image](https://github.com/user-attachments/assets/b3dc5e13-4795-4527-a93c-6ade57ec350e)

When we click on the caret on the right, we should be able to see the current button "Download queries without results" like in the current version:
![Image](https://github.com/user-attachments/assets/5ef1565f-5000-4af9-8c13-bcbd2fa8a2c5)
But we talked of renaming this button and calling it "Download zero-result queries". I don't know what kind of dropdown button we should us here, do you want to discuss it?

- Edit buttons: we could have only one button "Edit batch search" and let users do both actions in the same BS form 


Also:

- I see that you use button-icon__label for batch search actions. Could we use this component but without the borders in order to match the design?
 ![Image](https://github.com/user-attachments/assets/90bed922-052a-41ac-9553-cbf143e59030)

- The icon here shouldn't be UserGear as we reserve UserGear for document recommendation. It should be User.
![Image](https://github.com/user-attachments/assets/83780a70-f739-4ea6-8113-28e8aec29493)

- As we changed the new BS form, I suggest we change 
1/ The icon of Phrase Match from Toggle to Quotes (in Phosphor) 
2/ Change the text "Phrase match: on" into "Do phrase match: yes"
3/ Change "Proximity: 1" into "Phrase changes: 1"

- I like that you used ProjectLabel (I changed it in Figma to match your idea in the design) but I wonder if we should use ProjectButton instead so users can right-click and access the search page or the project page from here. Wdyt?

**Comment by caro3801** [comment]
- [x] use User icon instead of UserGear 
- [x] remove action buttons borders 
- [x] The icon of Phrase Match from Toggle to Quotes (in Phosphor)
- [x] Change the text "Phrase match: on" into "Do phrase match: yes" + add pluralization
- [x] Change "Proximity: 1" into "Phrase changes: 1" => I used "Sentence" instead of "phrase" as a translation + add pluralization
- [x] Use of project label: it's a link so they can right-click and access the search page or the project page from here
- [ ] add download dropdown - wip

**Comment by Soliine** [comment]
Excellent ! 

Congratulations on this big work 💯
