### ISSUE TITLE
design system: project insight widget metric

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1509]
**Preview**

![Image](https://github.com/user-attachments/assets/f7dee926-873e-46de-972b-6b5e9267873d)
![Image](https://github.com/user-attachments/assets/9bc7c345-3008-4ae4-8392-41dd6d33caee)

**Comment by caro3801** [comment]
I named it widget barometer instead of project insight widget metric
The first two elements have borders since all variant have borders. it can be removed if preferred.
default responsive behavior is row wrap.
component is here: https://icij.github.io/datashare-client/?path=/docs/components-widget-widgetbarometer--docs

**Comment by Soliine** [comment]
Excellent!
I am thinking that the elements are links so we should have a hover state for them. Wdyt?

**Comment by caro3801** [comment]
Render with hover state (border color change): 

![Image](https://github.com/user-attachments/assets/fc5d9cc2-618e-46ef-a94b-20fff00431e6)
