### ISSUE TITLE
design system: entity popover

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#1513]
**Preview**

![Image](https://github.com/user-attachments/assets/33e4529f-209b-41bd-879e-24434b8f413c)

**Comment by caro3801** [comment]
code is here https://github.com/ICIJ/datashare-client/commit/a97c7ec59ab2f282ab7938ead177625a1393797f
component is here : https://icij.github.io/datashare-client/?path=/docs/components-entitypopover-entitypopover--docs
component mentions is a bit interactive : https://icij.github.io/datashare-client/?path=/story/components-entitypopover-entitypopovermentions--default

**Comment by pirhoo** [comment]
Note those components' doc is now under new links:

* https://icij.github.io/datashare-client/?path=/docs/components-entity-entitypopover-entitypopover--docs
* https://icij.github.io/datashare-client/?path=/docs/components-entity-entitypopover-entitypopovermentions--docs

**Comment by caro3801** [comment]
Thanks for the feedback

- [x] styling issues: reuse of navigation tab 
- [x] project buttons : change for project button instead of project link
- [x] code: renaming navigation tab to tab group navigation -same for tabs => tab group

entity popover: https://icij.github.io/datashare-client/?path=/docs/components-entity-entitypopover-entitypopover--docs
tab group: https://icij.github.io/datashare-client/?path=/docs/components-tabgroup-tabgroup--docs

- [ ] width variation: can you be more specific? is it due to the scroll bar ?
- [ ] zoom issue: do you zoom with storybook or the browser? I can't reproduce the issue but I think we can fix the popover position at the risk of making it out of see.

**Comment by Soliine** [comment]
Thanks for the changes! 

- Here is the width variation. The Info tab makes the popover less large:
https://github.com/user-attachments/assets/c8b64f4e-d868-4e72-b617-86df12da47cc

- Regarding the zoom issue, it's happening when my Chrome window (not the Storybook zoom indeed) is at 90% zoomed out. Here is how it looks:
https://github.com/user-attachments/assets/e7f5f61b-530e-4390-971a-9bca3c51e549

It's also with this resolution that I see the border here (which I don't see in the 100% resolution):
<img width="166" alt="Screenshot 2024-09-05 at 10 30 17" src="https://github.com/user-attachments/assets/13a33091-d0fc-40bd-a10d-424de42802b0">

**Comment by pirhoo** [comment]
I guess the issue with arrow is the same issue we noticed yesterday on the language dropdown selector. It's a bug from Bootstrap on every popover:

https://getbootstrap.com/docs/5.3/components/popovers/#overview

Unfortunately we can't do much about it, zoom in web browser can create a lot of bugs.

**Comment by Soliine** [comment]
Ok let's wait for them to fix it! Thanks for investigating!

**Comment by caro3801** [comment]
fix: add fixed witdh for the entity popover tabs : https://github.com/ICIJ/datashare-client/commit/3b7fd3eb0e14398543425b734b5e809380c9c904

**Comment by Soliine** [comment]
Well done! It's perfect!
