### ISSUE TITLE
NER via HTTP API?

### ISSUE THREAD

**Issue by pudo** [ICIJ/datashare#2]
Congratulations to making the datashare code available! I think the multi-NER pipeline is really cool, so allow me two questions:

a) are you planning an API endpoint that makes the chained NER available independently of the content extraction and indexing parts of the application? It'd be really cool if there was an API that just allowed submitting a bunch of strings and then returned an annotated version of them.

b) Is it possible to boot the server without defining an ES index at all (i.e. neither remote nor the built-in)?

**Comment by bamthomas** [comment]
hello @pudo, thank you for your feedback. 

a) On a pure API point of view it is independent from the extract/indexing. The idea was to define a small API jar with business models (including index/extract but with no deps). Then having implementations of the NLP pipelines, in independent modules. Would is be enough for your needs ?

b) we've chosen (but it isn't a strong architecture decision) to use ES as persistence between extract/index and NLP extraction : NLP clients are reading documents text content from ES. Maybe we could abstract persistence layer in a DDD repository service. What would you think ?

**Comment by pudo** [comment]
hello @bamthomas thanks for your help - especially the comment on (b): I hadn't realised that ES is used as persistence between the extraction and analysis steps. This makes a lot of sense, especially in conjunction with the pub/sub scheme you describe.

I'm really excited about what you're proposing with (a), as it would make it possible to deploy some of datashare as a microservice and get the benefit of the combined NER pipeline. Obviously I cannot tell to what extent it is on your roadmap, and my Java is sufficiently rusty to cause more harm than good, but you'd have a very very admiring user if you ended up exposing the NER solo :)

**Comment by bamthomas** [comment]
hi @pudo sorry for the delay.

This should be possible now. You can run datashare with docker like this : 

    docker run -ti -p 8080:8080 -v /home/bruno/dist/:/home/datashare/dist icij/datashare:0.10 -m NER -w

A bit of explanation : 
- `-w` tells datashare to run the webserver. It is launched on 8080 that's why the port is mapped for docker
- `-m NER` runs datashare without index at all on a stateless mode
- `-v /path/to/dist:/home/datashare/dist` maps the directory where the NLP models will be read (and downloaded if they don't exist)

Then you can curl it like this : 

    curl -i localhost:8080/ner/findNames/CORENLP --data-binary @path/to/a/file.txt

The last path part (CORENLP) is the framework. You can choose it among CORENLP, GATENLP, IXAPIPE, MITIE or OPENNLP.

Tell me if it fit your needs.

**Comment by bamthomas** [comment]
I close this issue, but don't hesitate to reopen it.

**Comment by pudo** [comment]
Wow, this is really cool. We've just refactored the NER microservice on our end, so it's a perfect time to play with chaining in more functionality. Going to give it a spin ASAP!
