### ISSUE TITLE
Option `--redisAddress` is ignored

### ISSUE THREAD

**Issue by laurent-girod** [ICIJ/datashare#23]
The option `--redisAddress` is ignored by DataShare.

Steps to reproduce:
- Set up a redis container called redis-test
- Ensure there is no running container called `redis`
- Specify `redis://redis-test:6379` as the redis address to datashare with --redisAddress
- Try to parse named entities in a document
- The extraction crash because `redis` is not a known host.

**Comment by bamthomas** [comment]
OK this is a dark part of datashare. In the project we inherited from [extract-lib](https://github.com/ICIJ/extract) a redisson redis queue for scan/parse files. 
The parameter is `--redisAddress`

We added a message bus that is on redis too (because it is lightweight and we already had a redis, but it could be for ex RabbitMQ or whatever). 
The parameter is `--messageBusAddress` 

So I guess in your case you should give the both : 
`--redisAddress redis://redis-test:6379 --messageBusAddress redis-test`
