### ISSUE TITLE
Adapt datashare to run in a k8s cluster

### ISSUE THREAD

**Issue by Mr-Reca** [ICIJ/datashare#413]
The script requires to use docker-compose.

If we want to deploy an Elasticsearch cluster and then run the UI in another machine, they cannot be connected.

Is there a way to create a YAML file or a Helm Chart?

**Comment by bamthomas** [comment]
which script ? `datashare.sh` ?

`datashare.sh` is using docker-compose because it was simpler to make the 3 services (elasticsearch, redis and datashare) running. But you can make it run alone, and it will scale horizontally (the only thing that is not working properly is configuration save and share between instances).

So yes there is a way because datashare can run on an isolated docker instance, you "just" have to provide the right parameters to the container to make it find elasticsearch, the database, redis and the filesystem where the documents are stored. You can try the help with `-h`to find those parameters.

You can find information here : https://github.com/ICIJ/datashare/wiki/Datashare-Server-Mode

**Comment by Mr-Reca** [comment]
Hi @bamthomas 

I was talking about `datashare.sh`

I've tried to create 3 pods, following the script, and the UI was no table to find elasticsearch. Maybe I need some additional configuration, but I was not able to investigate it.

I'll look the Datashare-Server-Mode. 

Thank you so much,

**Comment by chriszs** [comment]
We run Datashare in k8s, but we do so in local mode with one pod for the UI and indexing. It's not optimal, but our user count is low. Here's our Helm chart: https://github.com/PublicI/datashare-deploy
