### ISSUE TITLE
Go back to all folders in Path Facet

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#44]
After clicking on a specific folder to navigate, unless I click on search and start the search over, I cant go back to previous folders to chose other folders to explore.

![dspath](https://user-images.githubusercontent.com/17233829/51327691-23c1ad00-1a72-11e9-96ee-80dab03ceed7.png)

**Comment by annelhote** [comment]
1. Build a tree like :
![screenshot from 2019-01-21 19-39-21](https://user-images.githubusercontent.com/1478919/51493082-5e01b600-1db4-11e9-8c3e-f35b7792a582.png)

**Comment by annelhote** [comment]
This is the expected behaviour of Datashare. The point is that any facet on the right column is updated according to the search results. That's why only the paths listed in the results are in the Path Facet, here "folder_02/folder_03". This can be changed by unselecting the button "Contextualize the search results with the facets:" in the settings.

**Comment by annelhote** [comment]
Set the contextualize search as False by default.
