### ISSUE TITLE
Datashare not compatible with Java > 8

### ISSUE THREAD

**Issue by martinszy** [ICIJ/datashare#458]
Hi, I just downloaded 6.3.4 deb file, installed with gdebi (which does not come stock in ubuntu 20.04, shockingly), then run the datashare command and got this output: https://gist.github.com/martinszy/483528f76ab25f425f7175e11d190aff

A browser window opened but no server was listening.

**Comment by martinszy** [comment]
I just found these other install instructions which are based on docker, but I have a feeling they are outdated: https://icij.gitbook.io/datashare/linux/install-datashare-on-linux

**Comment by bamthomas** [comment]
hello @martinszy yes the documentation is about installation with docker.

The error you have occurs because you don't have JRE 8.

You can install it alongside with the default one (11 for ubuntu 20) with :
```
sudo apt install openjdk-8-jre 
```

Then you can launch datashare with 
```
JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjre-amd64 datashare
```

But yes we have to fix this making datashare compatible with most recent Java versions.

**Comment by martinszy** [comment]
Yes, this works. Command was
```$ JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/ datashare```

**Comment by bamthomas** [comment]
thanks for closing the issue, I reopen it to use for our taskboard for the fix task
