### ISSUE TITLE
Backend proxy to elasticsearch should also forward body with GET 

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#465]
This should work (body is currently ignored):

```bash
curl -X GET http://localhost:8080/api/index/search/local-datashare/_search\?size\=0 -d'{ "query": { "match": { "type": "NamedEntity" } } }' -H 'Content-Type: application/json' 
```

**Comment by bamthomas** [comment]
That's a tough one. 

The reason is that there are discussions around HTTP specs to know if it is legal for a GET to have a body. It seems that 
1. the spec doesn't forbid a GET with a body
2. but it shouldn't have any meaning i.e. that the response should not depend on it

cf [this SO thread](https://stackoverflow.com/questions/978061/http-get-with-request-body)

We are depending on [OkHttp](https://square.github.io/okhttp/) :
- for the tests (because FluentRestTest are using okhttp)
- for the production code because the requests are sent to ES with okhttp

Okhttp is disabling by API to send a body with a GET. I initiated a pull request to change the API but I'm pretty sure that they won't accept it. It seems that there is very few servers that are using it but [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/guide/current/_empty_search.html#get_vs_post).

All that said, there is a way to send a GET request without a body, with source and source_content_type parameters and urlencoded ES query :
```
curl 'http://elasticsearch:9200/_search?source=%7B%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%7D&source_content_type=application/json'
```
So there are 3 ways of doing this  :
1. datashare API is accepting a GET with a body and transform the request with source/source_content_type
2. datashare client is directly sending the request with source/source_content_type
3. we change the http library in DS backend to use one that allows to send GET with body

What do you think?
