### ISSUE TITLE
Identical batch searches but one failure and one success

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#547]
I added one batch searches and it led to 2 batch searches in the results (ID: 324e329e-91f5-4ef5-9cac-c45cad522799 and e8dc68fc-44bf-48f2-aa45-f68086dadbd4).
One is a success, the other one is a failure ("listener timeout after waiting for [50000] ms") but they have the exact same results per query.

**Comment by mvanzalu** [comment]
@bamthomas can it be linked to #462 ?

**Comment by bamthomas** [comment]
yes it is the same as #462 and if the same batch search can have at the same time success and error it is because of the availability of ES at the time the batch search is executed : if ES is not under pressure the search will success and if it is under pressure (maintenance, indexing, several users searches), then the batch search will have each search during a little more time, and as we are sometimes at the limit of the timeout, then it will fail.

The only things that can be done is : 
- optimizing search requests if possible
- improving the infrastructure (ES cluster)

**Comment by Soliine** [comment]
As we're working on improving performance, we close this issue and will reopen if neede.
