### ISSUE TITLE
Insights: add a "no creation date" bar

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#588]
**Is your feature request related to a problem? Please describe.**
In Insights, I see in the "Filter by folder" that there are 31 documents but in the bar chart, there are only 6 documents because only 6 have a creation date. 

**Describe the solution you'd like**
I suggest we add a bar at the beginning of the bar chart with the caption "No creation date".

**Describe alternatives you've considered**
I considered counting only the documents with creation date in the "Filter by folder" module but it would be incomplete compared to the "Search in document"'s count. 

<img width="1080" alt="Screenshot 2020-08-11 at 15 15 18" src="https://user-images.githubusercontent.com/17233829/89902091-4b451100-dbe6-11ea-9449-4f3129f9993a.png">
<img width="797" alt="Screenshot 2020-08-11 at 14 59 39" src="https://user-images.githubusercontent.com/17233829/89902100-4da76b00-dbe6-11ea-9360-2ed5ffeb0349.png">
<img width="910" alt="Screenshot 2020-08-11 at 15 21 41" src="https://user-images.githubusercontent.com/17233829/89902198-72034780-dbe6-11ea-998e-d2438235eeb7.png">

**Comment by annelhote** [comment]
1. There are multiple reasons why a document is not here in the barchart:
  * The document has no creation date at all
  * The creation date of the document is prior to January 1. 1970
  * The creation date of the document is posterior to the current date
2. I do not think that adding a new bar is the good solution because it will not be accurate. I would rather add a sentence saying that X data are missing in the barchart for being inaccurate.

**Comment by Soliine** [comment]
Thanks for the explanations. I like your idea. To be fully transparent, I would suggest a tooltip when users hover the sentence "X data are missing in the barchart" with your explanation:
"There are multiple reasons why a document is not here in the barchart:
- The document has no creation date at all
- The creation date of the document is prior to January 1. 1970
- The creation date of the document is posterior to the current date"
What do you think?

**Comment by annelhote** [comment]
Ok. Done.
