### ISSUE TITLE
500 server errors on DS for certain fuzzy searches, even if able to query Elasticsearch directly 

### ISSUE THREAD

**Issue by madoleary** [ICIJ/datashare#710]
**Describe the bug**
A user encountered a server error when trying to perform a certain fuzzy search on Datashare. Graylogs showed a `listener timeout` error on Elasticsearch. However, the same fuzzy search was made successfully via a direct query to Elasticsearch. 

When a different, more generic fuzzy search was made on Datashare, results were returned successfully, indicating that this is perhaps not an issue for all fuzzy searches. 

**To Reproduce**
1. Via Datashare, launch the fuzzy search attempted by the user (in the same index, try the more generic fuzzy search `name~ AND day~`)

**Expected behavior**
Results, even if there are none, should be returned instead of a server error.

**Comment by annelhote** [comment]
Could not reproduced in local.
Could reproduced in prod, with complex fuzzy search but sometimes even with the `name~ AND day~`.

**Comment by annelhote** [comment]
* Could not reproduced in local.
* Could reproduced in prod, with complex fuzzy search but sometimes even with the `name~ AND day~`.
* There is a [request timeout](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-configuration.html#_basic_options) of 60 seconds on [our ES requests](https://github.com/ICIJ/datashare-client/blob/master/src/api/elasticsearch.js#L161).
* Currently our shards for the last project are between 74GB to 78GB. A good size should be around 20GB. We should definitely review it like advised [here](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/size-your-shards.html#shard-size-recommendation).

**Comment by mvanzalu** [comment]
- Tested queries (querystring) directly to ES wtih curl --> some complex fuzzy search can take more than 60 seconds
- This is indeed more than the 60 seconds request timeout on ES requests
- A previous performance benchmark has been made between ElasticSearch and Datashare (sending requests to ElasticSearch)
   - Results showed that both had very near latency performances
   - ![6931e49d21a2cb4d8f26be49a4c801df58e0dcb4](https://user-images.githubusercontent.com/35509100/104035800-d85eb700-51d2-11eb-9ed9-9d00dff346fa.png) (time in ms) ![4e6fa793a8445a98e36d183640c424d7417d44b2](https://user-images.githubusercontent.com/35509100/104035847-e7de0000-51d2-11eb-9045-f08e7afe498c.png) 
- This issue is related to our ongoing ElasticSearch optimizations
