### ISSUE TITLE
Search in docs: highlight (1/2)

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#75]
- [x] number of occurrences
- [x] new highlight

**Comment by annelhote** [comment]
@Soliine any screenshots about this new feature or maybe I am free ? ;)

**Comment by Soliine** [comment]
@annelhote here is one:
![Sd4](https://user-images.githubusercontent.com/17233829/54993669-b1fe6600-4fc2-11e9-8e18-75a185128c3b.png)

**Comment by annelhote** [comment]
Thank you !

**Comment by Soliine** [comment]
You're welcome :)

**Comment by annelhote** [comment]
It may be not straightforward to count the number of occurrences of a word per document in Elasticsearch : https://discuss.elastic.co/t/number-of-occurrences-of-a-particular-word-in-a-field/129569/5. So I choose to bring back the whole content of a doc, which we did not do until now, to do a regexp on it after the elasticsearch response.

**Comment by annelhote** [comment]
https://confluence.icij.org/display/NP/ES+-+Retrieve+content+or+not

**Comment by annelhote** [comment]
After discussion we decided not to retrieve the document content on the ES query to search for documents, because it could be really heavy. Because of that we will not be able to display the number of query terms occurrences in the search results column. So we will display the number of query terms occurrences in the document view part, in the extracted text tab.

**Comment by annelhote** [comment]
Randomly generates the colour of the query terms highlight.

**Comment by annelhote** [comment]
To solve : the colours between the query term on top and the term occurrences on the doc don't match !

**Comment by annelhote** [comment]
@Soliine Do you remember what we meant by "icon as prefix" ?

**Comment by annelhote** [comment]
Splitted into two parts : #166.
