### ISSUE TITLE
Secure batch download

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#810]
**Is your feature request related to a problem? Please describe.**

The epic #804 is about batch download of document from a corpus.
We would like to add a secure download functionality to avoid unauthorized people from accessing sensitive data 

**Describe the solution you'd like**

We'd like to add a password on the zip archive 

**Describe alternatives you've considered**

The content could also be encrypted  with GPG and use the ICIJ gpg key repository
We could talk about the system team about the best security option.

**Comment by bamthomas** [comment]
Actually it has not been implemented as an extension because it would have been more complex.

We added two options : 
* `smtpUrl` that is taking a smtp server url to send the email 
* `batchDownloadEncrypt` (boolean) that tells the batch download daemon whether it should  encrypt the zip files

**Comment by Soliine** [comment]
As seen with Bruno, in order to inform users about the encryption and the steps they need to take, let's add "This file is encrypted. The password has been sent to you by email."

<img width="616" alt="Screenshot 2021-11-02 at 17 31 43" src="https://user-images.githubusercontent.com/17233829/139906587-c195c0a6-83f1-4ffa-a616-ed79f90717aa.png">
