### ISSUE TITLE
Searching with 'Name' field leads to 0 results while it should

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#841]
**Describe the bug**
Searching with 'Name' field in the dropdown menu leads to 0 results while it should.

**To Reproduce**
1. Go to https://datashare-demo.icij.org/#/?q=%22inter%20ikea%22&from=0&size=100&sort=pathReverse&index=luxleaks&field=title&stamp=xgzyah
2. See that there is no results
3. Now if you search metadata.tika_metadata_resourcename:"Inter Ikea", it finds 8 documents

**Comment by bamthomas** [comment]
This issue is strongly correlated to the corpus of documents : it is a mapping between field names, and actual document fields in elasticsearch.  

We can trust  `document.name` because it's the file name, but the other fields `document.metadata.*`are related to the metadata extracted by tika. And they depends on the document type. 

MV added the `resourcename` field but it could happen again with other documents.
