### ISSUE TITLE
Server-Mode unable to PUT /api/index/local-datashare

### ISSUE THREAD

**Issue by yakomisar** [ICIJ/datashare#881]
I am trying to initiate server mode of Datashare and encounter an authentication issue during login. 
OS: macOS Monterey 12.3
Docker images with ip addresses:
1. elasticsearch 8.1.1 - 172.17.0.2
2. icij/datashare 10.1.1
3. postgres 10.20 - 172.17.0.3
4. redis latest - 172.17.0.4
My script for starting up:
docker run -p 8080:8080 -ti icij/datashare:10.1.1 --mode SERVER --redisAddress redis://[172.17.0.4:6379](http://172.17.0.4:6379/) --elasticsearchAddress https://172.17.0.2:9200/ --messageBusAddress 172.17.0.4 --dataSourceUrl "jdbc:postgresql://[172.17.0.3:5432/dsdatabase?user=postgres&password=my-secret-pwd](http://172.17.0.3:5432/dsdatabase?user=postgres&password=my-secret-pwd)" --rootHost localhost:8080 --authFilter org.icij.datashare.session.BasicAuthAdaptorFilter

Then, after login to the localhost:8080 using my credentials that were added to redis I receive some kind of error. Please find attached. Could you please help me?

**Comment by yakomisar** [comment]
[error_log.txt](https://github.com/ICIJ/datashare/files/8410343/error_log.txt)

**Comment by FacetedGlass** [comment]
Recently I tried to run Datashare in server mode and encountered the same problem. Please share the solution if you find one.

**Comment by randolphgow** [comment]
So, this issue seems like what I am getting as well. The error i get when i check the log of the DataShare Server docker is: 
`2022-04-04 13:48:13,548 [Worker: RequestDispatcher: Thread-28] ERROR Fluent - Unable to PUT /api/index/local-datashare
2022-04-04 13:48:13,553 [Worker: RequestDispatcher: Thread-28] ERROR Fluent - Unexpected error:
org.icij.datashare.text.indexing.elasticsearch.ElasticsearchConfiguration$ConfigurationException: java.net.ConnectException: Timeout connecting to [/172.19.0.4:9200]`

From this, I can deduce that the elastic search setup is to blame for the error. Although, this error only comes up when I login to DataShare and not when I launch the DataShare server. Let me quickly state the steps i took to get to this error. I will try to make it as detailed as possible just in case I made an obvious mistake in the initial stages, and someone here will be able to point it out to me.

Step 1 - Create a Redis docker container (address in bridge network of docker:`172.17.0.3`)
`docker run --name myredis -p 6379:6379 -d redis`

Step 2 - Create a  Postgresql docker container (address in bridge network of docker:`172.17.0.2`)
`docker run --name mypostgres -e POSTGRES_PASSWORD=mypass1234 -d postgres:10.20`

Step 3 - Create an Elastic Search docker container (address in bridge network of docker:`172.17.0.4`)
`docker run -d --name elasticsearch -p 9200:9200 -e "discovery.type=single-node" elasticsearch:7.17.2`

Step 4 - Create a DataShare docker container 
`docker run -p 8080:8080 -ti icij/datashare:10.1.1 --mode SERVER \ --redisAddress redis://172.17.0.3:6379 \ --elasticsearchAddress https://172.19.0.4:9200 \ --messageBusAddress 172.17.0.3 \ --dataSourceUrl "jdbc:postgresql://172.17.0.2:5432/dsbase?user=postgres&password=mypass1234" \ --rootHost localhost:8080 \ --authFilter org.icij.datashare.session.BasicAuthAdaptorFilter`

Step 5 - Create a user in Redis with access to DataShare
`redis:6379> set randy '{"uid":"randy", "password":"<base64pass>", "groups_by_applications":{"datashare": ["testproject"]}}}'`

Once all that is done, I try to login to DataShare and on providing the username and password I get the following screen and the error i mentioned above:
![image](https://user-images.githubusercontent.com/3090126/161921391-edcfcb72-5817-4c9b-9b64-d1d6a00b9f53.png)

**Comment by pirhoo** [comment]
Hello, 

this is a error in the frontend. This line should not be executed in SERVER mode:
https://github.com/ICIJ/datashare-client/blob/master/src/core/Core.js#L182

We'll push a fix shortly. Thanks!
